ALTER TABLE wallet_db.wallets ADD COLUMN IF NOT EXISTS type VARCHAR(50) DEFAULT 'RETAIL';
ALTER TABLE wallet_db.wallets ADD COLUMN IF NOT EXISTS status VARCHAR(50) DEFAULT 'ACTIVE';
ALTER TABLE wallet_db.wallets ADD COLUMN IF NOT EXISTS currency VARCHAR(10) DEFAULT 'NGN';
ALTER TABLE wallet_db.wallets ADD COLUMN IF NOT EXISTS balance BIGINT DEFAULT 0;
ALTER TABLE wallet_db.wallets ADD COLUMN IF NOT EXISTS tier_level VARCHAR(50) DEFAULT 'TIER_1';
ALTER TABLE wallet_db.wallets ADD COLUMN IF NOT EXISTS daily_limit BIGINT DEFAULT 50000;
ALTER TABLE wallet_db.wallets ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP;
