ALTER TABLE wallet_db.users ADD COLUMN IF NOT EXISTS full_name VARCHAR(255);
ALTER TABLE wallet_db.users ADD COLUMN IF NOT EXISTS email VARCHAR(255) UNIQUE;
ALTER TABLE wallet_db.users ADD COLUMN IF NOT EXISTS phone_number VARCHAR(50) UNIQUE;
ALTER TABLE wallet_db.users ADD COLUMN IF NOT EXISTS bvn VARCHAR(50);
ALTER TABLE wallet_db.users ADD COLUMN IF NOT EXISTS nin VARCHAR(50);
ALTER TABLE wallet_db.users ADD COLUMN IF NOT EXISTS role VARCHAR(50) DEFAULT 'CITIZEN';
ALTER TABLE wallet_db.users ADD COLUMN IF NOT EXISTS status VARCHAR(50) DEFAULT 'ACTIVE';
ALTER TABLE wallet_db.users ADD COLUMN IF NOT EXISTS last_login_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE wallet_db.users ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP;
