ALTER TABLE offline_db.devices ADD COLUMN IF NOT EXISTS hardware_id VARCHAR(255);
ALTER TABLE offline_db.devices ADD COLUMN IF NOT EXISTS os_version VARCHAR(50);
ALTER TABLE offline_db.devices ADD COLUMN IF NOT EXISTS app_version VARCHAR(50);
ALTER TABLE offline_db.devices ADD COLUMN IF NOT EXISTS trusted_status VARCHAR(50) DEFAULT 'TRUSTED';
ALTER TABLE offline_db.devices ADD COLUMN IF NOT EXISTS last_sync_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE offline_db.vouchers ADD COLUMN IF NOT EXISTS encrypted_data TEXT;
ALTER TABLE offline_db.vouchers ADD COLUMN IF NOT EXISTS expires_at TIMESTAMP WITH TIME ZONE;
